export const tags = [
  { cat: 'Angular', tag: '@Attribute' },
  { cat: 'Angular', tag: '@ContentChild' },
  { cat: 'Angular', tag: '@HostBinding' },
  { cat: 'Angular', tag: '@HostListener' },
  { cat: 'Angular', tag: '@Input' },
  { cat: 'Angular', tag: '@Inject' },
  { cat: 'Angular', tag: '@Injectable' },
  { cat: 'Angular', tag: '@Optional' },
  { cat: 'Angular', tag: '@Output' },
  { cat: 'Angular', tag: '@Skip' },
  { cat: 'Angular', tag: '@SkipSelf' },
  { cat: 'Angular', tag: '@ViewChild' },
  { cat: 'Angular', tag: '@ViewChildren' },
  { cat: 'Angular', tag: '*ngFor' },
  { cat: 'Angular', tag: '*ngIf' },
  { cat: 'Angular', tag: '*ngSwitch' },
  { cat: 'Angular', tag: ':host' },
  { cat: 'Angular', tag: ':host-context' },
  { cat: 'Angular', tag: '::ng-deep' },
  { cat: 'Angular', tag: '<ng-container>' },
  { cat: 'Angular', tag: '<ng-content>' },
  { cat: 'Angular', tag: '<ng-template>' },
  { cat: 'Angular', tag: '<router-outlet>' },
  { cat: 'Angular', tag: 'Accessibility' },
  { cat: 'Angular', tag: 'ActivatedRoute' },
  { cat: 'Angular', tag: 'ActivatedRouteSnapshot' },
  { cat: 'Angular', tag: 'Angular Elements' },
  { cat: 'Angular', tag: 'Angular Universal' },
  { cat: 'Angular', tag: 'Animations' },
  { cat: 'Angular', tag: 'Architecture' },
  { cat: 'Angular', tag: 'APP_INITIALIZER' },
  { cat: 'Angular', tag: 'Attribute Binding' },
  { cat: 'Angular', tag: 'Builders' },
  { cat: 'Angular', tag: 'CanActivate' },
  { cat: 'Angular', tag: 'CanActivateChild' },
  { cat: 'Angular', tag: 'CanDeactivate' },
  { cat: 'Angular', tag: 'CanLoad' },
  { cat: 'Angular', tag: 'CanMatch' },
  { cat: 'Angular', tag: 'CLI' },
  { cat: 'Angular', tag: 'Change Detection' },
  { cat: 'Angular', tag: 'ChangeDetectorRef' },
  { cat: 'Angular', tag: 'Class Binding' },
  { cat: 'Angular', tag: 'Components' },
  { cat: 'Angular', tag: 'Component Factory' },
  { cat: 'Angular', tag: 'Content Projection' },
  { cat: 'Angular', tag: 'ControlContainer' },
  { cat: 'Angular', tag: 'ControlValueAccessor' },
  { cat: 'Angular', tag: 'Data Binding' },
  { cat: 'Angular', tag: 'Data Transfer' },
  { cat: 'Angular', tag: 'Event Binding' },
  { cat: 'Angular', tag: 'Debugging' },
  { cat: 'Angular', tag: 'Decorators' },
  { cat: 'Angular', tag: 'Dependency Injection' },
  { cat: 'Angular', tag: 'Deployment' },
  { cat: 'Angular', tag: 'Directives' },
  { cat: 'Angular', tag: 'ElementRef' },
  { cat: 'Angular', tag: 'ENVIRONMENT_INITIALIZER' },
  { cat: 'Angular', tag: 'Environments' },
  { cat: 'Angular', tag: 'EventEmitter' },
  { cat: 'Angular', tag: 'ExpressionChangedAfterItHasBeenCheckedError' },
  { cat: 'Angular', tag: 'Extended Diagnostics' },
  { cat: 'Angular', tag: 'FormBuilder' },
  { cat: 'Angular', tag: 'FormArray' },
  { cat: 'Angular', tag: 'FormControl' },
  { cat: 'Angular', tag: 'FormGroup' },
  { cat: 'Angular', tag: 'Forms' },
  { cat: 'Angular', tag: 'HttpClient' },
  { cat: 'Angular', tag: 'HttpContext' },
  { cat: 'Angular', tag: 'HttpInterceptors' },
  { cat: 'Angular', tag: 'HttpParams' },
  { cat: 'Angular', tag: 'Hot Module Replacement' },
  { cat: 'Angular', tag: 'InjectionToken' },
  { cat: 'Angular', tag: 'Internationalization' },
  { cat: 'Angular', tag: 'Interpolation' },
  { cat: 'Angular', tag: 'Ivy' },
  { cat: 'Angular', tag: 'Lazy Loading' },
  { cat: 'Angular', tag: 'Libraries' },
  { cat: 'Angular', tag: 'Lifecycle Hooks' },
  { cat: 'Angular', tag: 'Modules' },
  { cat: 'Angular', tag: 'NavigationCancel' },
  { cat: 'Angular', tag: 'NavigationCancellationCode' },
  { cat: 'Angular', tag: 'NgZone' },
  { cat: 'Angular', tag: 'One-Way Data Binding' },
  { cat: 'Angular', tag: 'OnPush' },
  { cat: 'Angular', tag: 'Optional Modules' },
  { cat: 'Angular', tag: 'ParamMap' },
  { cat: 'Angular', tag: 'PWA' },
  { cat: 'Angular', tag: 'Performance' },
  { cat: 'Angular', tag: 'Pipes' },
  { cat: 'Angular', tag: 'Preloading' },
  { cat: 'Angular', tag: 'Property Binding' },
  { cat: 'Angular', tag: 'Query Params' },
  { cat: 'Angular', tag: 'QueryList' },
  { cat: 'Angular', tag: 'Reactive Forms' },
  { cat: 'Angular', tag: 'Resolve' },
  { cat: 'Angular', tag: 'Route Guards' },
  { cat: 'Angular', tag: 'Route Params' },
  { cat: 'Angular', tag: 'RouteReuseStrategy' },
  { cat: 'Angular', tag: 'Routing' },
  { cat: 'Angular', tag: 'SPA' },
  { cat: 'Angular', tag: 'Schematics' },
  { cat: 'Angular', tag: 'Services' },
  { cat: 'Angular', tag: 'Standalone Components' },
  { cat: 'Angular', tag: 'Style Binding' },
  { cat: 'Angular', tag: 'Template Reference Variable' },
  { cat: 'Angular', tag: 'Template Driven Forms' },
  { cat: 'Angular', tag: 'TemplateRef' },
  { cat: 'Angular', tag: 'TestBed' },
  { cat: 'Angular', tag: 'Title' },
  { cat: 'Angular', tag: 'Two-Way Data Binding' },
  { cat: 'Angular', tag: 'Typed Forms' },
  { cat: 'Angular', tag: 'Update' },
  { cat: 'Angular', tag: 'Validation' },
  { cat: 'Angular', tag: 'ViewContainerRef' },
  { cat: 'Angular', tag: 'ViewEncapsulation' },
  { cat: 'Angular', tag: 'createApplication()' },
  { cat: 'Angular', tag: 'createComponent()' },
  { cat: 'Angular', tag: 'createEmbeddedView()' },
  { cat: 'Angular', tag: 'detectChanges()' },
  { cat: 'Angular', tag: 'getTitle()' },
  { cat: 'Angular', tag: 'inject()' },
  { cat: 'Angular', tag: 'let-*' },
  { cat: 'Angular', tag: 'markForCheck()' },
  { cat: 'Angular', tag: 'ng build' },
  { cat: 'Angular', tag: 'ng completion' },
  { cat: 'Angular', tag: 'ng serve' },
  { cat: 'Angular', tag: 'ng test' },
  { cat: 'Angular', tag: 'ngAfterContentChecked()' },
  { cat: 'Angular', tag: 'ngAfterContentInit()' },
  { cat: 'Angular', tag: 'ngAfterViewChecked()' },
  { cat: 'Angular', tag: 'ngAfterViewInit()' },
  { cat: 'Angular', tag: 'ngComponentOutlet' },
  { cat: 'Angular', tag: 'ngDoCheck()' },
  { cat: 'Angular', tag: 'ngModel' },
  { cat: 'Angular', tag: 'ngOnChanges()' },
  { cat: 'Angular', tag: 'ngOnDestroy()' },
  { cat: 'Angular', tag: 'ngOnInit()' },
  { cat: 'Angular', tag: 'ngPlural' },
  { cat: 'Angular', tag: 'ngPluralCase' },
  { cat: 'Angular', tag: 'ngTemplateOutlet' },
  { cat: 'Angular', tag: 'ngTemplateOutletContext' },
  { cat: 'Angular', tag: 'ngTemplateOutletInjector' },
  { cat: 'Angular', tag: 'patchValue()' },
  { cat: 'Angular', tag: 'routerLink' },
  { cat: 'Angular', tag: 'routerLinkActive' },
  { cat: 'Angular', tag: 'runInContext' },
  { cat: 'Angular', tag: 'setTitle()' },
  { cat: 'Angular', tag: 'setValue()' },
  { cat: 'Angular', tag: 'trackBy' },
  { cat: 'Angular', tag: 'useClass' },
  { cat: 'Angular', tag: 'useExisting' },
  { cat: 'Angular', tag: 'useFactory' },
  { cat: 'Angular', tag: 'useValue' },

  { cat: 'Misc', tag: 'Auth' },
  { cat: 'Misc', tag: 'Autocomplete' },
  { cat: 'Misc', tag: 'Bash Scripts' },
  { cat: 'Misc', tag: 'BreakpointObserver' },
  { cat: 'Misc', tag: 'Bundle Size' },
  { cat: 'Misc', tag: 'Caching' },
  { cat: 'Misc', tag: 'Charts' },
  { cat: 'Misc', tag: 'CI/CD' },
  { cat: 'Misc', tag: 'CORS' },
  { cat: 'Misc', tag: 'Community' },
  { cat: 'Misc', tag: 'Configuration' },
  { cat: 'Misc', tag: 'Cookies' },
  { cat: 'Misc', tag: 'CRUD' },
  { cat: 'Misc', tag: 'CSRF' },
  { cat: 'Misc', tag: 'Custom' },
  { cat: 'Misc', tag: 'DOM Manipulation' },
  { cat: 'Misc', tag: 'Design Patterns' },
  { cat: 'Misc', tag: 'Destructuring' },
  { cat: 'Misc', tag: 'Domain Driven Design' },
  { cat: 'Misc', tag: 'Dot Files' },
  { cat: 'Misc', tag: 'Dynamic' },
  { cat: 'Misc', tag: 'ESLint' },
  { cat: 'Misc', tag: 'Errors' },
  { cat: 'Misc', tag: 'Facade Design Pattern' },
  { cat: 'Misc', tag: 'Feature Flags' },
  { cat: 'Misc', tag: 'File Upload' },
  { cat: 'Misc', tag: 'Geolocation' },
  { cat: 'Misc', tag: 'IntersectionObserver' },
  { cat: 'Misc', tag: 'JSON' },
  { cat: 'Misc', tag: 'JWT' },
  { cat: 'Misc', tag: 'Linters' },
  { cat: 'Misc', tag: 'localStorage' },
  { cat: 'Misc', tag: 'Maps' },
  { cat: 'Misc', tag: 'Menu' },
  { cat: 'Misc', tag: 'Micro Frontends' },
  { cat: 'Misc', tag: 'Microservices' },
  { cat: 'Misc', tag: 'Mixins' },
  { cat: 'Misc', tag: 'Mobile' },
  { cat: 'Misc', tag: 'Module Federation' },
  { cat: 'Misc', tag: 'Monorepo' },
  { cat: 'Misc', tag: 'PDF' },
  { cat: 'Misc', tag: 'Pagination' },
  { cat: 'Misc', tag: 'Path Mapping' },
  { cat: 'Misc', tag: 'Phone' },
  { cat: 'Misc', tag: 'Productivity' },
  { cat: 'Misc', tag: 'Responsive' },
  { cat: 'Misc', tag: 'Scrolling' },
  { cat: 'Misc', tag: 'SEO' },
  { cat: 'Misc', tag: 'SMS' },
  { cat: 'Misc', tag: 'SSR' },
  { cat: 'Misc', tag: 'Sanitization' },
  { cat: 'Misc', tag: 'Search' },
  { cat: 'Misc', tag: 'Security' },
  { cat: 'Misc', tag: 'Service Workers' },
  { cat: 'Misc', tag: 'Slider' },
  { cat: 'Misc', tag: 'Skeletons' },
  { cat: 'Misc', tag: 'Spinner' },
  { cat: 'Misc', tag: 'State Management' },
  { cat: 'Misc', tag: 'Styles' },
  { cat: 'Misc', tag: 'Webpack' },
  { cat: 'Misc', tag: 'Web Components' },
  { cat: 'Misc', tag: 'Web Workers' },
  { cat: 'Misc', tag: 'XSS' },
  { cat: 'Misc', tag: 'iframe' },

  { cat: 'Testing', tag: 'Assertions' },
  { cat: 'Testing', tag: 'Code Coverage' },
  { cat: 'Testing', tag: 'Cypress' },
  { cat: 'Testing', tag: 'Dummies' },
  { cat: 'Testing', tag: 'Fakes' },
  { cat: 'Testing', tag: 'Jasmine' },
  { cat: 'Testing', tag: 'Jest' },
  { cat: 'Testing', tag: 'Karma' },
  { cat: 'Testing', tag: 'Mocks' },
  { cat: 'Testing', tag: 'Protractor' },
  { cat: 'Testing', tag: 'Stubs' },
  { cat: 'Testing', tag: 'Testing' },
  { cat: 'Testing', tag: 'Unit Testing' },
  { cat: 'Testing', tag: 'E2E Testing' },
  { cat: 'Testing', tag: 'TDD' },

  { cat: 'TypeScript', tag: 'AST' },
  { cat: 'TypeScript', tag: 'Async/await' },
  { cat: 'TypeScript', tag: 'Async Pipe' },
  { cat: 'TypeScript', tag: 'Constructor' },
  { cat: 'TypeScript', tag: 'Enums' },
  { cat: 'TypeScript', tag: 'Generics' },
  { cat: 'TypeScript', tag: 'Generators' },
  { cat: 'TypeScript', tag: 'Getters/Setters' },
  { cat: 'TypeScript', tag: 'Interfaces' },
  { cat: 'TypeScript', tag: 'Nullish Coalescing' },
  { cat: 'TypeScript', tag: 'Promises' },
  { cat: 'TypeScript', tag: 'Strict Mode' },
  { cat: 'TypeScript', tag: 'Tagged Union Types' },
  { cat: 'TypeScript', tag: 'TypeScript' },
  { cat: 'TypeScript', tag: 'Utility Types' },

  { cat: 'Angular-Material', tag: 'Angular Material' },
  { cat: 'Angular-Material', tag: 'Angular CDK' },
  { cat: 'Angular-Material', tag: 'Button' },
  { cat: 'Angular-Material', tag: 'Checkbox' },
  { cat: 'Angular-Material', tag: 'Chips' },
  { cat: 'Angular-Material', tag: 'cdkTrapFocus' },
  { cat: 'Angular-Material', tag: 'Clipboard' },
  { cat: 'Angular-Material', tag: 'Component Harness' },
  { cat: 'Angular-Material', tag: 'Data Table' },
  { cat: 'Angular-Material', tag: 'Datepicker' },
  { cat: 'Angular-Material', tag: 'Dialog' },
  { cat: 'Angular-Material', tag: 'Drag and Drop' },
  { cat: 'Angular-Material', tag: 'Form Field' },
  { cat: 'Angular-Material', tag: 'Overlay' },
  { cat: 'Angular-Material', tag: 'Portals' },
  { cat: 'Angular-Material', tag: 'Progress' },
  { cat: 'Angular-Material', tag: 'Select' },
  { cat: 'Angular-Material', tag: 'Sidenav' },
  { cat: 'Angular-Material', tag: 'Tabs' },
  { cat: 'Angular-Material', tag: 'Theming' },
  { cat: 'Angular-Material', tag: 'Toolbar' },
  { cat: 'Angular-Material', tag: 'Tooltip' },

  { cat: 'NgRx', tag: 'NgRx' },
  { cat: 'NgRx', tag: 'Actions' },
  { cat: 'NgRx', tag: 'ComponentStore' },
  { cat: 'NgRx', tag: 'NgRx Data' },
  { cat: 'NgRx', tag: 'Effects' },
  { cat: 'NgRx', tag: 'NgRX' },
  { cat: 'NgRx', tag: 'Reducers' },
  { cat: 'NgRx', tag: 'Selectors' },

  { cat: 'RxJS', tag: 'AsyncSubject' },
  { cat: 'RxJS', tag: 'BehaviorSubject' },
  { cat: 'RxJS', tag: 'Hot vs Cold' },
  { cat: 'RxJS', tag: 'Marble Testing' },
  { cat: 'RxJS', tag: 'Observables' },
  { cat: 'RxJS', tag: 'ReplaySubject' },
  { cat: 'RxJS', tag: 'RxJS' },
  { cat: 'RxJS', tag: 'Schedulers' },
  { cat: 'RxJS', tag: 'Service with a Subject' },
  { cat: 'RxJS', tag: 'Subject' },
  { cat: 'RxJS', tag: 'Subscriptions' },
  { cat: 'RxJS', tag: 'Void Subject' },
  { cat: 'RxJS', tag: 'ajax()' },
  { cat: 'RxJS', tag: 'bindCallback()' },
  { cat: 'RxJS', tag: 'bindNodeCallback()' },
  { cat: 'RxJS', tag: 'catchError()' },
  { cat: 'RxJS', tag: 'combineLatest()' },
  { cat: 'RxJS', tag: 'combineLatestAll()' },
  { cat: 'RxJS', tag: 'combineLatestWith()' },
  { cat: 'RxJS', tag: 'complete' },
  { cat: 'RxJS', tag: 'concat()' },
  { cat: 'RxJS', tag: 'concatMap()' },
  { cat: 'RxJS', tag: 'concatAll()' },
  { cat: 'RxJS', tag: 'count()' },
  { cat: 'RxJS', tag: 'debounce()' },
  { cat: 'RxJS', tag: 'debounceTime()' },
  { cat: 'RxJS', tag: 'defer()' },
  { cat: 'RxJS', tag: 'dematerialize()' },
  { cat: 'RxJS', tag: 'distinct()' },
  { cat: 'RxJS', tag: 'distinctUntilChanged()' },
  { cat: 'RxJS', tag: 'exhaustAll()' },
  { cat: 'RxJS', tag: 'exhaustMap()' },
  { cat: 'RxJS', tag: 'expand()' },
  { cat: 'RxJS', tag: 'filter()' },
  { cat: 'RxJS', tag: 'finalize()' },
  { cat: 'RxJS', tag: 'first()' },
  { cat: 'RxJS', tag: 'forkJoin()' },
  { cat: 'RxJS', tag: 'from()' },
  { cat: 'RxJS', tag: 'fromEvent()' },
  { cat: 'RxJS', tag: 'fromEventPattern()' },
  { cat: 'RxJS', tag: 'generate()' },
  { cat: 'RxJS', tag: 'iif()' },
  { cat: 'RxJS', tag: 'interval()' },
  { cat: 'RxJS', tag: 'map()' },
  { cat: 'RxJS', tag: 'materialize()' },
  { cat: 'RxJS', tag: 'merge()' },
  { cat: 'RxJS', tag: 'mergeAll()' },
  { cat: 'RxJS', tag: 'mergeMap()' },
  { cat: 'RxJS', tag: 'multicast()' },
  { cat: 'RxJS', tag: 'of()' },
  { cat: 'RxJS', tag: 'pairwise()' },
  { cat: 'RxJS', tag: 'partition()' },
  { cat: 'RxJS', tag: 'pipe()' },
  { cat: 'RxJS', tag: 'pluck()' },
  { cat: 'RxJS', tag: 'race()' },
  { cat: 'RxJS', tag: 'range()' },
  { cat: 'RxJS', tag: 'retry()' },
  { cat: 'RxJS', tag: 'retryWhen()' },
  { cat: 'RxJS', tag: 'scan()' },
  { cat: 'RxJS', tag: 'share()' },
  { cat: 'RxJS', tag: 'shareReplay()' },
  { cat: 'RxJS', tag: 'startWith()' },
  { cat: 'RxJS', tag: 'switchAll()' },
  { cat: 'RxJS', tag: 'switchMap()' },
  { cat: 'RxJS', tag: 'take()' },
  { cat: 'RxJS', tag: 'takeUntil()' },
  { cat: 'RxJS', tag: 'tap()' },
  { cat: 'RxJS', tag: 'throwError()' },
  { cat: 'RxJS', tag: 'timer()' },
  { cat: 'RxJS', tag: 'unsubscribe()' },
  { cat: 'RxJS', tag: 'withLatestFrom()' },
  { cat: 'RxJS', tag: 'zip()' },

  { cat: '3rd Party', tag: 'AG Grid' },
  { cat: '3rd Party', tag: 'Akita' },
  { cat: '3rd Party', tag: 'AngularFire' },
  { cat: '3rd Party', tag: 'Auth0' },
  { cat: '3rd Party', tag: 'AWS' },
  { cat: '3rd Party', tag: 'Azure' },
  { cat: '3rd Party', tag: 'Bootstrap' },
  { cat: '3rd Party', tag: 'Capacitor' },
  { cat: '3rd Party', tag: 'D3' },
  { cat: '3rd Party', tag: 'Docker' },
  { cat: '3rd Party', tag: 'DevTools' },
  { cat: '3rd Party', tag: 'Electron' },
  { cat: '3rd Party', tag: 'ExpressJS' },
  { cat: '3rd Party', tag: 'Firebase' },
  { cat: '3rd Party', tag: 'flex-layout' },
  { cat: '3rd Party', tag: 'Font Awesome' },
  { cat: '3rd Party', tag: 'GitHub Actions' },
  { cat: '3rd Party', tag: 'GitHub Pages' },
  { cat: '3rd Party', tag: 'Google' },
  { cat: '3rd Party', tag: 'Google Analytics' },
  { cat: '3rd Party', tag: 'Google Maps' },
  { cat: '3rd Party', tag: 'Google Pay' },
  { cat: '3rd Party', tag: 'GraphQL' },
  { cat: '3rd Party', tag: 'Hasura' },
  { cat: '3rd Party', tag: 'Ionic' },
  { cat: '3rd Party', tag: 'JSDoc' },
  { cat: '3rd Party', tag: 'Kendo UI' },
  { cat: '3rd Party', tag: 'Kubernetes' },
  { cat: '3rd Party', tag: 'MongoDB' },
  { cat: '3rd Party', tag: 'NestJS' },
  { cat: '3rd Party', tag: '.Net' },
  { cat: '3rd Party', tag: 'NextJS' },
  { cat: '3rd Party', tag: 'NGXS' },
  { cat: '3rd Party', tag: 'NPM' },
  { cat: '3rd Party', tag: 'Nx' },
  { cat: '3rd Party', tag: 'OpenLayers' },
  { cat: '3rd Party', tag: 'Prettier' },
  { cat: '3rd Party', tag: 'PrimeNG' },
  { cat: '3rd Party', tag: 'Scully' },
  { cat: '3rd Party', tag: 'SingleSPA' },
  { cat: '3rd Party', tag: 'Storybook' },
  { cat: '3rd Party', tag: 'TailwindCSS' },
  { cat: '3rd Party', tag: 'TensorFlowJS' },
  { cat: '3rd Party', tag: 'VSCode' },
  { cat: '3rd Party', tag: 'Webstorm' },
  { cat: '3rd Party', tag: 'reCAPTCHA' },
];
// GOOD