export const tags = [
  { category: 'Angular', tag: 'AOT' },
  { category: 'Angular', tag: 'Accessibility' },
  { category: 'Angular', tag: 'Angular Elements' },
  { category: 'Angular', tag: 'AngularJS' },
  { category: 'Angular', tag: 'Angular Universal' },
  { category: 'Angular', tag: 'Angular Workspace' },
  { category: 'Angular', tag: 'Animations' },
  { category: 'Angular', tag: 'Architecture' },
  { category: 'Angular', tag: 'Attribute Binding' },
  {
    category: 'Angular',
    tag: 'Builders',
    rel: ['CLI', 'ng build', 'ng serve', 'ng test'],
  },
  { category: 'Angular', tag: 'CLI' },
  { category: 'Angular', tag: 'Change Detection' },
  { category: 'Angular', tag: 'ChangeDetectorRef', rel: ['detectChanges()'] },
  { category: 'Angular', tag: 'Components' },
  { category: 'Angular', tag: 'Component Factory' },
  { category: 'Angular', tag: 'Container Presenter' },
  { category: 'Angular', tag: 'Content Projection' },
  { category: 'Angular', tag: 'Data Binding' },
  { category: 'Angular', tag: 'Data Transfer' },
  { category: 'Angular', tag: 'Debugging' },
  { category: 'Angular', tag: 'Decorators' },
  { category: 'Angular', tag: 'Dependency Injection' },
  { category: 'Angular', tag: 'Deployment' },
  { category: 'Angular', tag: 'Directives' },
  { category: 'Angular', tag: 'ElementRef' },
  { category: 'Angular', tag: 'Environments' },
  { category: 'Angular', tag: 'Event Binding' },
  { category: 'Angular', tag: 'EventEmitter' },
  { category: 'Angular', tag: 'Form Builder' },
  { category: 'Angular', tag: 'Forms' },
  { category: 'Angular', tag: 'HttpClient' },
  { category: 'Angular', tag: 'HttpContext', rel: ['HttpInterceptor'] },
  { category: 'Angular', tag: 'HttpInterceptors' },
  { category: 'Angular', tag: ':host' },
  { category: 'Angular', tag: ':host-context' },
  { category: 'Angular', tag: 'Hot Module Replacement' },
  { category: 'Angular', tag: 'InjectionToken' },
  { category: 'Angular', tag: 'Internationalization', rel: ['i18n'] },
  { category: 'Angular', tag: 'Interpolation' },
  { category: 'Angular', tag: 'Ivy' },
  { category: 'Angular', tag: 'Lazy Loading' },
  { category: 'Angular', tag: 'Libraries' },
  { category: 'Angular', tag: 'Lifecycle Hooks' },
  { category: 'Angular', tag: 'Modules' },
  { category: 'Angular', tag: 'NgModel' },
  { category: 'Angular', tag: 'NgZone' },
  { category: 'Angular', tag: 'One-Way Data Binding' },
  { category: 'Angular', tag: 'Optional Modules' },
  { category: 'Angular', tag: 'PWA', alt: ['Progressive Web App'] },
  { category: 'Angular', tag: 'Performance' },
  { category: 'Angular', tag: 'Pipes' },
  { category: 'Angular', tag: 'Preloading' },
  { category: 'Angular', tag: 'Property Binding' },
  { category: 'Angular', tag: 'QueryList' },
  { category: 'Angular', tag: 'SPA' },
  { category: 'Angular', tag: 'Schematics' },
  { category: 'Angular', tag: 'Services' },
  { category: 'Angular', tag: 'Standalone Components' },
  { category: 'Angular', tag: 'Style Binding' },
  { category: 'Angular', tag: 'Template Reference Variable' },
  { category: 'Angular', tag: 'Template Driven Forms' },
  { category: 'Angular', tag: 'TemplateRef' },
  { category: 'Angular', tag: 'Tour of Heroes' },
  { category: 'Angular', tag: 'Two-Way Data Binding' },
  { category: 'Angular', tag: 'Update' },
  { category: 'Angular', tag: 'ViewChild' },
  { category: 'Angular', tag: 'ViewEncapsulation' },
  { category: 'Angular', tag: 'ng build' },
  { category: 'Angular', tag: 'ng serve' },
  { category: 'Angular', tag: 'ng test' },
  { category: 'Angular', tag: 'ng-container' },
  { category: 'Angular', tag: 'ng-content' },
  { category: 'Angular', tag: 'ng-deep' },
  { category: 'Angular', tag: 'ng-template' },
  { category: 'Angular', tag: 'ngAfterContentChecked' },
  { category: 'Angular', tag: 'ngAfterContentInit' },
  { category: 'Angular', tag: 'ngContent' },
  { category: 'Angular', tag: 'ngComponentOutlet' },
  { category: 'Angular', tag: 'ngDoCheck' },
  { category: 'Angular', tag: 'ngFor' },
  { category: 'Angular', tag: 'ngIf' },
  { category: 'Angular', tag: 'ngAfterContentChecked' },
  { category: 'Angular', tag: 'ngAfterContentChecked' },
  { category: 'Angular', tag: 'ngAfterContentInit' },
  { category: 'Angular', tag: 'ngAfterViewChecked' },
  { category: 'Angular', tag: 'ngAfterViewInit' },
  { category: 'Angular', tag: 'ngDoCheck' },
  { category: 'Angular', tag: 'ngOnChanges' },
  { category: 'Angular', tag: 'ngOnDestroy' },
  { category: 'Angular', tag: 'ngOnInit' },
  { category: 'Angular', tag: 'ngPlural' },
  { category: 'Angular', tag: 'ngPluralCase' },
  { category: 'Angular', tag: 'ngSwitch' },
  { category: 'Angular', tag: 'ngTemplateOutlet' },
  { category: 'Angular', tag: 'ngTemplateOutletInjector' },
  { category: 'Angular', tag: 'onPush' },
  { category: 'Angular', tag: 'String Interpolation' },
  { category: 'Angular', tag: 'trackBy' },
  { category: 'Angular', tag: 'useFactory' },
  { category: 'Angular', tag: 'viewContainerRef' },

  { category: 'Angular-decorators', tag: '@Attribute' },
  { category: 'Angular-decorators', tag: '@ContentChild' },
  { category: 'Angular-decorators', tag: '@HostBinding' },
  { category: 'Angular-decorators', tag: '@HostListener' },
  { category: 'Angular-decorators', tag: '@Input' },
  { category: 'Angular-decorators', tag: '@Inject' },
  { category: 'Angular-decorators', tag: '@Output' },
  { category: 'Angular-decorators', tag: '@ViewChild' },
  { category: 'Angular-decorators', tag: '@ViewChildren' },

  { category: 'Angular-forms', tag: 'ControlContainer' },
  { category: 'Angular-forms', tag: 'ControlValueAccessor' },
  { category: 'Angular-forms', tag: 'FormArray' },
  { category: 'Angular-forms', tag: 'FormControl' },
  { category: 'Angular-forms', tag: 'FormGroup' },
  { category: 'Angular-forms', tag: 'Reactive Forms' },
  { category: 'Angular-forms', tag: 'Validation' },

  { category: 'Angular-routing', tag: 'ActivatedRoute' },
  { category: 'Angular-routing', tag: 'canActivate' },
  { category: 'Angular-routing', tag: 'canDeactivate' },
  { category: 'Angular-routing', tag: 'Route Guards' },
  { category: 'Angular-routing', tag: 'Route Params', alt: 'Query Params' },
  { category: 'Angular-routing', tag: 'RouteReuseStrategy' },
  { category: 'Angular-routing', tag: 'routerLinkActive' },
  { category: 'Angular-routing', tag: 'routerLinkActiveOptions' },
  { category: 'Angular-routing', tag: 'Routing' },
  { category: 'Angular-routing', tag: 'router-outlet' },

  { category: 'Misc', tag: 'Auth' },
  { category: 'Misc', tag: 'Autocomplete' },
  { category: 'Misc', tag: 'Bash Scripts' },
  { category: 'Misc', tag: 'Bundle Size' },
  { category: 'Misc', tag: 'Caching' },
  { category: 'Misc', tag: 'CI/CD' },
  { category: 'Misc', tag: 'CORS' },
  { category: 'Misc', tag: 'Community' },
  { category: 'Misc', tag: 'Cookies' },
  { category: 'Misc', tag: 'CRUD' },
  { category: 'Misc', tag: 'CSRF' },
  { category: 'Misc', tag: 'Custom' },
  { category: 'Misc', tag: 'DOM Manipulation' },
  { category: 'Misc', tag: 'Design Patterns' },
  { category: 'Misc', tag: 'Destructuring' },
  { category: 'Misc', tag: 'Domain Driven Design' },
  { category: 'Misc', tag: 'Dot Files' },
  { category: 'Misc', tag: 'Dynamic' },
  { category: 'Misc', tag: 'ESLint' },
  { category: 'Misc', tag: 'Errors' },
  { category: 'Misc', tag: 'Feature Flags' },
  { category: 'Misc', tag: 'File Upload' },
  { category: 'Misc', tag: 'Intersection Observer' },
  { category: 'Misc', tag: 'JWT' },
  { category: 'Misc', tag: 'Linters' },
  { category: 'Misc', tag: 'Local Storage' },
  { category: 'Misc', tag: 'Menu' },
  { category: 'Misc', tag: 'Micro Frontends' },
  { category: 'Misc', tag: 'Microservices' },
  { category: 'Misc', tag: 'Mixins' },
  { category: 'Misc', tag: 'Module Federation' },
  { category: 'Misc', tag: 'Monorepo' },
  { category: 'Misc', tag: 'Open Source' },
  { category: 'Misc', tag: 'PDF' },
  { category: 'Misc', tag: 'Pagination' },
  { category: 'Misc', tag: 'Path Mapping' },
  { category: 'Misc', tag: 'Phone' },
  { category: 'Misc', tag: 'Productivity' },
  { category: 'Misc', tag: 'ResizeObserver' },
  { category: 'Misc', tag: 'Responsive' },
  { category: 'Misc', tag: 'SSR' },
  { category: 'Misc', tag: 'Sanitization' },
  { category: 'Misc', tag: 'Search' },
  { category: 'Misc', tag: 'Security' },
  { category: 'Misc', tag: 'Service Workers' },
  { category: 'Misc', tag: 'State Management' },
  { category: 'Misc', tag: 'Styles' },
  { category: 'Misc', tag: 'Web Components' },
  { category: 'Misc', tag: 'Web Sockets' },
  { category: 'Misc', tag: 'Web Workers' },
  { category: 'Misc', tag: 'git' },

  { category: 'Testing', tag: 'Assertions' },
  { category: 'Testing', tag: 'Code Coverage' },
  { category: 'Testing', tag: 'Cypress' },
  { category: 'Testing', tag: 'Dummies' },
  { category: 'Testing', tag: 'Fakes' },
  { category: 'Testing', tag: 'Jasmine' },
  { category: 'Testing', tag: 'Jest' },
  { category: 'Testing', tag: 'Karma' },
  { category: 'Testing', tag: 'Mocks' },
  { category: 'Testing', tag: 'Protractor' },
  { category: 'Testing', tag: 'Stubs' },
  { category: 'Testing', tag: 'Testing' },
  { category: 'Testing', tag: 'Unit Testing' },
  { category: 'Testing', tag: 'E2E Testing' },

  { category: 'TypeScript', tag: 'AST' },
  { category: 'TypeScript', tag: 'Async Pipe' },
  { category: 'TypeScript', tag: 'Constructor' },
  { category: 'TypeScript', tag: 'Enums' },
  { category: 'TypeScript', tag: 'Generics' },
  { category: 'TypeScript', tag: 'Generators' },
  { category: 'TypeScript', tag: 'Getters/Setters' },
  { category: 'TypeScript', tag: 'Interfaces' },
  { category: 'TypeScript', tag: 'Nullish Coalescing' },
  { category: 'TypeScript', tag: 'Promises' },
  { category: 'TypeScript', tag: 'Strict Mode' },
  { category: 'TypeScript', tag: 'Tagged Union Types' },
  { category: 'TypeScript', tag: 'TypeScript' },
  { category: 'TypeScript', tag: 'Utility Types' },

  { category: 'Angular-Material', tag: 'Angular Material' },
  { category: 'Angular-Material', tag: 'Angular CDK' },
  { category: 'Angular-Material', tag: 'Button' },
  { category: 'Angular-Material', tag: 'Checkbox' },
  { category: 'Angular-Material', tag: 'Chips' },
  { category: 'Angular-Material', tag: 'Component Harness' },
  { category: 'Angular-Material', tag: 'Datepicker' },
  { category: 'Angular-Material', tag: 'Dialog' },
  { category: 'Angular-Material', tag: 'Drag and Drop' },
  { category: 'Angular-Material', tag: 'Infinite Scroll' },
  { category: 'Angular-Material', tag: 'Portals' },
  { category: 'Angular-Material', tag: 'Progress' },
  { category: 'Angular-Material', tag: 'Slider' },
  { category: 'Angular-Material', tag: 'Spinner' },
  { category: 'Angular-Material', tag: 'Tabs' },
  { category: 'Angular-Material', tag: 'Theming' },
  { category: 'Angular-Material', tag: 'Virtual Scroll' },
  { category: 'Angular-Material', tag: 'Tooltip' },

  { category: 'NgRx', tag: 'NgRx' },
  { category: 'NgRx', tag: 'Actions' },
  { category: 'NgRx', tag: 'ComponentStore' },
  { category: 'NgRx', tag: 'NgRx Data' },
  { category: 'NgRx', tag: 'Effects' },
  { category: 'NgRx', tag: 'NgRX Entity' },
  { category: 'NgRx', tag: 'Reducers' },
  { category: 'NgRx', tag: 'Selectors' },
  { category: 'NgRx', tag: 'createFeature' },

  { category: 'RxJS', tag: 'AsyncSubject' },
  { category: 'RxJS', tag: 'BehaviorSubject' },
  { category: 'RxJS', tag: 'Creation Operators' },
  { category: 'RxJS', tag: 'Hot vs Cold' },
  { category: 'RxJS', tag: 'Marble Testing' },
  { category: 'RxJS', tag: 'Observables' },
  { category: 'RxJS', tag: 'Observer' },
  { category: 'RxJS', tag: 'ReplaySubject' },
  { category: 'RxJS', tag: 'RxJS' },
  { category: 'RxJS', tag: 'Schedulers' },
  { category: 'RxJS', tag: 'Service with a Subject' },
  { category: 'RxJS', tag: 'Subject' },
  { category: 'RxJS', tag: 'Subscriptions' },
  { category: 'RxJS', tag: 'Void Subject' },
  { category: 'RxJS', tag: 'catchError' },
  { category: 'RxJS', tag: 'combineLatestAll' },
  { category: 'RxJS', tag: 'concatMap' },
  { category: 'RxJS', tag: 'concatAll' },
  { category: 'RxJS', tag: 'debounceTime' },
  { category: 'RxJS', tag: 'distinctUntilChanged' },
  { category: 'RxJS', tag: 'exhaustAll' },
  { category: 'RxJS', tag: 'exhaustMap' },
  { category: 'RxJS', tag: 'finalize' },
  { category: 'RxJS', tag: 'map' },
  { category: 'RxJS', tag: 'mergeAll' },
  { category: 'RxJS', tag: 'mergeMap' },
  { category: 'RxJS', tag: 'multicast' },
  { category: 'RxJS', tag: 'pluck' },
  { category: 'RxJS', tag: 'range' },
  { category: 'RxJS', tag: 'scan' },
  { category: 'RxJS', tag: 'share' },
  { category: 'RxJS', tag: 'shareReplay' },
  { category: 'RxJS', tag: 'startWith' },
  { category: 'RxJS', tag: 'switchAll' },
  { category: 'RxJS', tag: 'switchMap' },
  { category: 'RxJS', tag: 'take' },
  { category: 'RxJS', tag: 'takeUntil' },
  { category: 'RxJS', tag: 'tap' },
  { category: 'RxJS', tag: 'unicast' },
  { category: 'RxJS', tag: 'withLatestFrom' },
  { category: 'RxJS', tag: 'zip' },

  { category: '3rd Party', tag: 'Akita' },
  { category: '3rd Party', tag: 'AngularFire' },
  { category: '3rd Party', tag: 'Auth0' },
  { category: '3rd Party', tag: 'AWS' },
  { category: '3rd Party', tag: 'Azure' },
  { category: '3rd Party', tag: 'Bootstrap' },
  { category: '3rd Party', tag: 'Capacitor' },
  { category: '3rd Party', tag: 'D3' },
  { category: '3rd Party', tag: 'Data Table' },
  { category: '3rd Party', tag: 'Docker' },
  { category: '3rd Party', tag: 'Electron' },
  { category: '3rd Party', tag: 'ExpressJS' },
  { category: '3rd Party', tag: 'Firebase' },
  { category: '3rd Party', tag: 'FlexLayoutModule' },
  { category: '3rd Party', tag: 'Font Awesome' },
  { category: '3rd Party', tag: 'GitHub Actions' },
  { category: '3rd Party', tag: 'GitHub Pages' },
  { category: '3rd Party', tag: 'Gitpod' },
  { category: '3rd Party', tag: 'Google' },
  { category: '3rd Party', tag: 'Google Analytics' },
  { category: '3rd Party', tag: 'Google Chart' },
  { category: '3rd Party', tag: 'Google Maps' },
  { category: '3rd Party', tag: 'Google Pay' },
  { category: '3rd Party', tag: 'GraphQL' },
  { category: '3rd Party', tag: 'Hasura' },
  { category: '3rd Party', tag: 'Ionic' },
  { category: '3rd Party', tag: 'JSDoc' },
  { category: '3rd Party', tag: 'Kendo UI' },
  { category: '3rd Party', tag: 'Kubernetes' },
  { category: '3rd Party', tag: 'Lodash-es' },
  { category: '3rd Party', tag: 'MongoDB' },
  { category: '3rd Party', tag: 'NestJS' },
  { category: '3rd Party', tag: 'NextJS' },
  { category: '3rd Party', tag: 'NGXS' },
  { category: '3rd Party', tag: 'Nx' },
  { category: '3rd Party', tag: 'Prettier' },
  { category: '3rd Party', tag: 'PrimeNG' },
  { category: '3rd Party', tag: 'PrismJS' },
  { category: '3rd Party', tag: 'Scully' },
  { category: '3rd Party', tag: 'Storybook' },
  { category: '3rd Party', tag: 'TailwindCSS' },
  { category: '3rd Party', tag: 'Transloco' },
  { category: '3rd Party', tag: 'Travis CI' },
  { category: '3rd Party', tag: 'VSCode' },
  { category: '3rd Party', tag: 'cloneDeep Lodash' },
  { category: '3rd Party', tag: 'ngx-bootstrap' },
  { category: '3rd Party', tag: 'ngx-logger' },
  { category: '3rd Party', tag: 'ngx-toastr' },
  { category: '3rd Party', tag: 'ngx-translate' },
  { category: '3rd Party', tag: 'reCAPTCHA' },
];
// GOOD