export const tags = {
  'Angular': [
    'AOT',
    'Angular',
    'Accessibility',
    'Angular Elements',
    'Angular 13',
    'Angular Universal',
    'Angular Workspace',
    'Animations',
    'Architecture',
    'Attribute Binding',
    'Builders',
    'CLI',
    'Change Detection',
    'Components',
    'Component Factory',
    'Container Presenter',
    'Content Projection',
    'Custom Directives',
    'Debugging',
    'Decorators',
    'Dependency Injection',
    'Deployment',
    'Directives',
    'Dynamic Components',
    'ElementRef',
    'Environments',
    'Event Binding',
    'EventEmitter',
    'Forms',
    'HttpClient',
    'HttpInterceptor',
    ':host',
    ':host-context',
    'Hot Module Replacement',
    'InjectionToken',
    'Internationalization',
    'Ivy',
    'Lazy Loading',
    'Libraries',
    'Lifecycle Hooks',
    'NgModules',
    'NgZone',
    'One-Way Data Binding',
    'Optional Modules',
    'PWA',
    'Pipes',
    'Preloading',
    'Property Binding',
    'QueryList',
    'SPA',
    'Schematics',
    'Services',
    'Standalone Components',
    'Style Binding',
    'Template-Driven Forms',
    'Tour of Heroes',
    'Two-Way Data Binding',
    'Update',
    'ViewChild',
    'ViewEncapsulation',
    'ng-container',
    'ng-content',
    'ng-deep',
    'ng-template',
    'ngAfterContentChecked',
    'ngAfterContentInit',
    'ngContent',
    'ngDoCheck',
    'ngFor',
    'ngIf',
    'ngOnChanges',
    'ngOnDestroy',
    'ngOnInit',
    'ngPlural',
    'ngPluralCase',
    'ngSwitch',
    'ngTemplateOutlet',
    'onPush',
    'trackBy',
    'useFactory',
    'viewContainerRef',
  ],
  'Angular-decorators': [
    '@Attribute',
    '@HostBinding',
    '@HostListener',
    '@Input',
    '@Inject',
    '@Output',
    '@ViewChild',
    '@ViewChildren',
  ],
  'Angular-forms': [
    'Angular-forms',
    'ControlContainer',
    'ControlValueAccessor',
    'FormArray',
    'FormControl',
    'FormGroup',
    'Reactive Forms',
    'Validation'
  ],
  'Angular-routing': [
    'ActivatedRoute',
    'canActivate',
    'canDeactivate',
    'Route Guards',
    'Route Params',
    'RouteReuseStrategy',
    'routerLinkActive',
    'routerLinkActiveOptions',
    'Router',
    'router-outlet',
    'Routing'
  ],
  'Misc': [
    'Auth',
    'Autocomplete',
    'Bash Scripts',
    'Bundle Size',
    'CORS',
    'Community',
    'Cookies',
    'CRUD',
    'CSRF',
    'DOM Manipulation',
    'Destructuring',
    'Domain Driven Design',
    'Dot Files',
    'ESLint',
    'Errors',
    'Factory Pattern',
    'Feature Flags',
    'Intersection Observer',
    'Iterator Pattern',
    'JWT',
    'Linters',
    'Local Storage',
    'Micro Frontends',
    'Microservices',
    'Mixins',
    'Module Federation',
    'Open Source',
    'PDF',
    'Pagination',
    'Path Mapping',
    'Performance',
    'Phone',
    'Pub/Sub Pattern',
    'ResizeObserver',
    'SSR',
    'Sanitization',
    'Security',
    'Service Workers',
    'State Management',
    'Styles',
    'Web Sockets',
    'git'
  ],
  'Testing': [
    'Assertions',
    'Code Coverage',
    'Cypress',
    'Dummies',
    'Fakes',
    'Jasmine',
    'Jest',
    'Karma',
    'Mocks',
    'Protractor',
    'Stubs',
    'Testing',
    'Unit Testing',
    'E2E Testing'
  ],
  'TypeScript': [
    'AST',
    'Async Pipe',
    'Constructor',
    'Enums',
    'Generics',
    'Generators',
    'Getters/Setters',
    'Interfaces',
    'Nullish Coalescing',
    'Promises',
    'Strict Mode',
    'Tagged Union Types',
    'TypeScript',
    'Utility Types'
  ],
  'Angular-Material': [
    'Angular Material',
    'Angular CDK',
    'Button',
    'Checkbox',
    'Chips',
    'Component Harness',
    'Dialog',
    'Infinite Scroll',
    'Portals',
    'Slider',
    'Spinner',
    'Tabs',
    'Theming',
    'Virtual Scroll',
    'Tooltip'
  ],
  'NgRx': [
    'NgRx',
    'Actions',
    'ComponentStore',
    'NgRx Data',
    'Effects',
    'NgRX Entity',
    'Reducers',
    'Selectors',
    'createFeature'
  ]
}





  





  





  { category: 'RxJS', tag: 'AsyncSubject' },
  { category: 'RxJS', tag: 'BehaviorSubject' },
  { category: 'RxJS', tag: 'Creation Operators' },
  { category: 'RxJS', tag: 'Hot vs Cold' },
  { category: 'RxJS', tag: 'Observables' },
  { category: 'RxJS', tag: 'Observer' },
  { category: 'RxJS', tag: 'ReplaySubject' },
  { category: 'RxJS', tag: 'RxJS' },
  { category: 'RxJS', tag: 'Schedulers' },
  { category: 'RxJS', tag: 'Service with a Subject' },
  { category: 'RxJS', tag: 'Subject' },
  { category: 'RxJS', tag: 'Subscriptions' },
  { category: 'RxJS', tag: 'Void Subject' },
  { category: 'RxJS', tag: 'catchError' },
  { category: 'RxJS', tag: 'combineLatestAll' },
  { category: 'RxJS', tag: 'concatMap' },
  { category: 'RxJS', tag: 'concatAll' },
  { category: 'RxJS', tag: 'debounceTime' },
  { category: 'RxJS', tag: 'distinctUntilChanged' },
  { category: 'RxJS', tag: 'exhaustAll' },
  { category: 'RxJS', tag: 'exhaustMap' },
  { category: 'RxJS', tag: 'map' },
  { category: 'RxJS', tag: 'mergeAll' },
  { category: 'RxJS', tag: 'mergeMap' },
  { category: 'RxJS', tag: 'multicast' },
  { category: 'RxJS', tag: 'range' },
  { category: 'RxJS', tag: 'share' },
  { category: 'RxJS', tag: 'shareReplay' },
  { category: 'RxJS', tag: 'startWith' },
  { category: 'RxJS', tag: 'switchAll' },
  { category: 'RxJS', tag: 'switchMap' },
  { category: 'RxJS', tag: 'takeUntil' },
  { category: 'RxJS', tag: 'unicast' },
  { category: 'RxJS', tag: 'withLatestFrom' },
  { category: 'RxJS', tag: 'zip' },

  { category: '3rd Party', tag: 'AngularFire 7' },
  { category: '3rd Party', tag: 'Azure' },
  { category: '3rd Party', tag: 'Bootstrap' },
  { category: '3rd Party', tag: 'Capacitor' },
  { category: '3rd Party', tag: 'Data Table' },
  { category: '3rd Party', tag: 'Docker' },
  { category: '3rd Party', tag: 'Electron' },
  { category: '3rd Party', tag: 'ExpressJS' },
  { category: '3rd Party', tag: 'Firebase' },
  { category: '3rd Party', tag: 'FlexLayoutModule' },
  { category: '3rd Party', tag: 'Font Awesome' },
  { category: '3rd Party', tag: 'GitHub Actions' },
  { category: '3rd Party', tag: 'GitHub Pages' },
  { category: '3rd Party', tag: 'Google' },
  { category: '3rd Party', tag: 'Google Analytics' },
  { category: '3rd Party', tag: 'Google Chart' },
  { category: '3rd Party', tag: 'Google Maps' },
  { category: '3rd Party', tag: 'Google Pay' },
  { category: '3rd Party', tag: 'GraphQL' },
  { category: '3rd Party', tag: 'Hasura' },
  { category: '3rd Party', tag: 'Ionic' },
  { category: '3rd Party', tag: 'JSDoc' },
  { category: '3rd Party', tag: 'Lodash-es' },
  { category: '3rd Party', tag: 'MongoDB' },
  { category: '3rd Party', tag: 'NestJS' },
  { category: '3rd Party', tag: 'NextJS' },
  { category: '3rd Party', tag: 'Ngxs' },
  { category: '3rd Party', tag: 'Nx' },
  { category: '3rd Party', tag: 'PrimeNG' },
  { category: '3rd Party', tag: 'PrismJS' },
  { category: '3rd Party', tag: 'Scully' },
  { category: '3rd Party', tag: 'Storybook' },
  { category: '3rd Party', tag: 'TailwindCSS' },
  { category: '3rd Party', tag: 'Transloco' },
  { category: '3rd Party', tag: 'VSCode' },
  { category: '3rd Party', tag: 'cloneDeep Lodash' },
  { category: '3rd Party', tag: 'ngx-bootstrap' },
  { category: '3rd Party', tag: 'ngx-logger' },
  { category: '3rd Party', tag: 'reCAPTCHA' },
];
