export const urlAutofillMatches = [
  {
    urlPartial: 'https://www.youtube.com/',
    type: 'video',
    sourceSite: 'YouTube',
    sourceUrl: 'https://youtube.com',
  },
  {
    urlPartial: 'https://dev.to',
    type: 'blog',
    sourceSite: 'DEV Community',
    sourceUrl: 'https://dev.to',
  },
  {
    urlPartial: 'https://www.spreaker.com/user/ng-conf',
    type: 'podcast',
    sourceSite: 'Spreaker',
    sourceUrl: 'https://www.spreaker.com',
    authorName: 'The Angular Show',
    authorUrl: 'https://www.spreaker.com/show/angular-show',
  },
  {
    urlPartial: 'https://adventuresinangular.com',
    type: 'podcast',
    sourceSite: 'Devchat.tv',
    sourceUrl: 'https://devchat.tv',
    authorName: 'Adventures In Angular',
    authorUrl: 'https://devchat.tv/show/adventures-in-angular/',
  },
  {
    urlPartial: 'https://open.spotify.com',
    type: 'podcast',
    sourceSite: 'Spotify',
    sourceUrl: 'https://open.spotify.com',
    authorName: 'Angular Master Podcast',
    authorUrl: 'https://open.spotify.com/show/1wgZAEEIoRZ8eP78LTbyZf',
  },
  {
    urlPartial: 'https://anchor.fm/ng-build-pod',
    type: 'podcast',
    sourceSite: 'Anchor',
    sourceUrl: 'https://anchor.fm/ng-build-pod/',
    authorName: 'ng build --pod',
    authorUrl: 'https://ngbuildpod.com',
  },
  {
    urlPartial: 'https://www.spreaker.com/user/14532324',
    type: 'podcast',
    sourceSite: 'Spreaker',
    sourceUrl: 'https://spreaker.com',
    authorName: 'Angular Experience',
    authorUrl: 'https://angular-experience.web.app/episodes',
  },
  {
    urlPartial: 'https://webrush.io',
    type: 'podcast',
    sourceSite: '',
    sourceUrl: '',
    authorName: 'Web Rush',
    authorUrl: 'https://webrush.io',
  },
  {
    urlPartial: 'https://indepth.dev',
    type: 'blog',
    sourceSite: 'inDepthDev',
    sourceUrl: 'https://indepth.dev/tutorials/angular',
  },
  {
    urlPartial: 'https://www.telerik.com/blogs',
    type: 'blog',
    sourceSite: 'Progress Telerik',
    sourceUrl: 'https://www.telerik.com/blogs',
  },
  {
    urlPartial: 'https://github.com/angular/angular/releases',
    type: 'release',
    sourceSite: 'GitHub Angular',
    sourceUrl: 'https://github.com/angular/angular/releases',
  },
];
